#pragma once

#define ICON_GLASS                       0xe800
#define ICON_MUSIC                       0xe801
#define ICON_SEARCH                      0xe802
#define ICON_MAIL                        0xe803
#define ICON_STAR_HALF                   0xe804
#define ICON_USER                        0xe805
#define ICON_USERS                       0xe806
#define ICON_VIDEO                       0xe807
#define ICON_VIDEOCAM                    0xe808
#define ICON_PICTURE                     0xe809
#define ICON_CAMERA                      0xe80a
#define ICON_CAMERA_ALT                  0xe80b
#define ICON_TH_LARGE                    0xe80c
#define ICON_TH                          0xe80d
#define ICON_TH_LIST                     0xe80e
#define ICON_OK                          0xe80f
#define ICON_OK_CIRCLED                  0xe810
#define ICON_OK_CIRCLED2                 0xe811
#define ICON_CANCEL                      0xe812
#define ICON_CANCEL_CIRCLED              0xe813
#define ICON_CANCEL_CIRCLED2             0xe814
#define ICON_PLUS                        0xe815
#define ICON_PLUS_CIRCLED                0xe816
#define ICON_MINUS                       0xe817
#define ICON_MINUS_CIRCLED               0xe818
#define ICON_HELP_CIRCLED                0xe819
#define ICON_INFO_CIRCLED                0xe81a
#define ICON_HOME                        0xe81b
#define ICON_LINK                        0xe81c
#define ICON_ATTACH                      0xe81d
#define ICON_LOCK                        0xe81e
#define ICON_LOCK_OPEN                   0xe81f
#define ICON_PIN                         0xe820
#define ICON_EYE                         0xe821
#define ICON_EYE_OFF                     0xe822
#define ICON_TAG                         0xe823
#define ICON_TAGS                        0xe824
#define ICON_BOOKMARK                    0xe825
#define ICON_FLAG                        0xe826
#define ICON_THUMBS_UP                   0xe827
#define ICON_THUMBS_DOWN                 0xe828
#define ICON_DOWNLOAD                    0xe829
#define ICON_UPLOAD                      0xe82a
#define ICON_FORWARD                     0xe82b
#define ICON_EXPORT                      0xe82c
#define ICON_PENCIL                      0xe82d
#define ICON_EDIT                        0xe82e
#define ICON_PRINT                       0xe82f
#define ICON_RETWEET                     0xe830
#define ICON_COMMENT                     0xe831
#define ICON_CHAT                        0xe832
#define ICON_BELL                        0xe833
#define ICON_ATTENTION                   0xe834
#define ICON_ATTENTION_CIRCLED           0xe835
#define ICON_LOCATION                    0xe836
#define ICON_TRASH_EMPTY                 0xe837
#define ICON_DOC                         0xe838
#define ICON_FOLDER                      0xe839
#define ICON_FOLDER_OPEN                 0xe83a
#define ICON_PHONE                       0xe83b
#define ICON_COG                         0xe83c
#define ICON_COG_ALT                     0xe83d
#define ICON_WRENCH                      0xe83e
#define ICON_BASKET                      0xe83f
#define ICON_CALENDAR                    0xe840
#define ICON_LOGIN                       0xe841
#define ICON_LOGOUT                      0xe842
#define ICON_VOLUME_OFF                  0xe843
#define ICON_VOLUME_DOWN                 0xe844
#define ICON_VOLUME_UP                   0xe845
#define ICON_HEADPHONES                  0xe846
#define ICON_CLOCK                       0xe847
#define ICON_BLOCK                       0xe848
#define ICON_RESIZE_FULL                 0xe849
#define ICON_RESIZE_SMALL                0xe84a
#define ICON_RESIZE_VERTICAL             0xe84b
#define ICON_RESIZE_HORIZONTAL           0xe84c
#define ICON_ZOOM_IN                     0xe84d
#define ICON_ZOOM_OUT                    0xe84e
#define ICON_DOWN_CIRCLED2               0xe84f
#define ICON_UP_CIRCLED2                 0xe850
#define ICON_DOWN_DIR                    0xe851
#define ICON_UP_DIR                      0xe852
#define ICON_LEFT_DIR                    0xe853
#define ICON_RIGHT_DIR                   0xe854
#define ICON_DOWN_OPEN                   0xe855
#define ICON_LEFT_OPEN                   0xe856
#define ICON_RIGHT_OPEN                  0xe857
#define ICON_UP_OPEN                     0xe858
#define ICON_DOWN_BIG                    0xe859
#define ICON_LEFT_BIG                    0xe85a
#define ICON_RIGHT_BIG                   0xe85b
#define ICON_UP_BIG                      0xe85c
#define ICON_RIGHT_HAND                  0xe85d
#define ICON_LEFT_HAND                   0xe85e
#define ICON_UP_HAND                     0xe85f
#define ICON_DOWN_HAND                   0xe860
#define ICON_CW                          0xe861
#define ICON_CCW                         0xe862
#define ICON_ARROWS_CW                   0xe863
#define ICON_SHUFFLE                     0xe864
#define ICON_PLAY                        0xe865
#define ICON_PLAY_CIRCLED2               0xe866
#define ICON_STOP                        0xe867
#define ICON_PAUSE                       0xe868
#define ICON_TO_END                      0xe869
#define ICON_TO_END_ALT                  0xe86a
#define ICON_TO_START                    0xe86b
#define ICON_TO_START_ALT                0xe86c
#define ICON_FAST_FW                     0xe86d
#define ICON_FAST_BW                     0xe86e
#define ICON_EJECT                       0xe86f
#define ICON_TARGET                      0xe870
#define ICON_SIGNAL                      0xe871
#define ICON_AWARD                       0xe872
#define ICON_INBOX                       0xe873
#define ICON_GLOBE                       0xe874
#define ICON_CLOUD                       0xe875
#define ICON_FLASH                       0xe876
#define ICON_UMBRELLA                    0xe877
#define ICON_FLIGHT                      0xe878
#define ICON_LEAF                        0xe879
#define ICON_FONT                        0xe87a
#define ICON_BOLD                        0xe87b
#define ICON_ITALIC                      0xe87c
#define ICON_TEXT_HEIGHT                 0xe87d
#define ICON_TEXT_WIDTH                  0xe87e
#define ICON_ALIGN_LEFT                  0xe87f
#define ICON_ALIGN_CENTER                0xe880
#define ICON_ALIGN_RIGHT                 0xe881
#define ICON_ALIGN_JUSTIFY               0xe882
#define ICON_LIST                        0xe883
#define ICON_INDENT_LEFT                 0xe884
#define ICON_INDENT_RIGHT                0xe885
#define ICON_SCISSORS                    0xe886
#define ICON_BRIEFCASE                   0xe887
#define ICON_OFF                         0xe888
#define ICON_ROAD                        0xe889
#define ICON_LIST_ALT                    0xe88a
#define ICON_QRCODE                      0xe88b
#define ICON_BARCODE                     0xe88c
#define ICON_BOOK                        0xe88d
#define ICON_ADJUST                      0xe88e
#define ICON_TINT                        0xe88f
#define ICON_CHECK                       0xe890
#define ICON_ASTERISK                    0xe891
#define ICON_GIFT                        0xe892
#define ICON_FIRE                        0xe893
#define ICON_MAGNET                      0xe894
#define ICON_CHART_BAR                   0xe895
#define ICON_CREDIT_CARD                 0xe896
#define ICON_FLOPPY                      0xe897
#define ICON_MEGAPHONE                   0xe898
#define ICON_KEY                         0xe899
#define ICON_TRUCK                       0xe89a
#define ICON_HAMMER                      0xe89b
#define ICON_LEMON                       0xe89c
#define ICON_HEART                       0xe89d
#define ICON_HEART_EMPTY                 0xe89e
#define ICON_STAR                        0xe89f
#define ICON_STAR_EMPTY                  0xe8a0
#define ICON_MOVE                        0xf047
#define ICON_LINK_EXT                    0xf08e
#define ICON_CHECK_EMPTY                 0xf096
#define ICON_BOOKMARK_EMPTY              0xf097
#define ICON_PHONE_SQUARED               0xf098
#define ICON_TWITTER                     0xf099
#define ICON_FACEBOOK                    0xf09a
#define ICON_GITHUB_CIRCLED              0xf09b
#define ICON_RSS                         0xf09e
#define ICON_HDD                         0xf0a0
#define ICON_CERTIFICATE                 0xf0a3
#define ICON_LEFT_CIRCLED                0xf0a8
#define ICON_RIGHT_CIRCLED               0xf0a9
#define ICON_UP_CIRCLED                  0xf0aa
#define ICON_DOWN_CIRCLED                0xf0ab
#define ICON_TASKS                       0xf0ae
#define ICON_FILTER                      0xf0b0
#define ICON_RESIZE_FULL_ALT             0xf0b2
#define ICON_BEAKER                      0xf0c3
#define ICON_DOCS                        0xf0c5
#define ICON_BLANK                       0xf0c8
#define ICON_MENU                        0xf0c9
#define ICON_LIST_BULLET                 0xf0ca
#define ICON_LIST_NUMBERED               0xf0cb
#define ICON_STRIKE                      0xf0cc
#define ICON_UNDERLINE                   0xf0cd
#define ICON_TABLE                       0xf0ce
#define ICON_MAGIC                       0xf0d0
#define ICON_PINTEREST_CIRCLED           0xf0d2
#define ICON_PINTEREST_SQUARED           0xf0d3
#define ICON_GPLUS_SQUARED               0xf0d4
#define ICON_GPLUS                       0xf0d5
#define ICON_MONEY                       0xf0d6
#define ICON_COLUMNS                     0xf0db
#define ICON_SORT                        0xf0dc
#define ICON_SORT_DOWN                   0xf0dd
#define ICON_SORT_UP                     0xf0de
#define ICON_MAIL_ALT                    0xf0e0
#define ICON_LINKEDIN                    0xf0e1
#define ICON_GAUGE                       0xf0e4
#define ICON_COMMENT_EMPTY               0xf0e5
#define ICON_CHAT_EMPTY                  0xf0e6
#define ICON_SITEMAP                     0xf0e8
#define ICON_PASTE                       0xf0ea
#define ICON_LIGHTBULB                   0xf0eb
#define ICON_EXCHANGE                    0xf0ec
#define ICON_DOWNLOAD_CLOUD              0xf0ed
#define ICON_UPLOAD_CLOUD                0xf0ee
#define ICON_USER_MD                     0xf0f0
#define ICON_STETHOSCOPE                 0xf0f1
#define ICON_SUITCASE                    0xf0f2
#define ICON_BELL_ALT                    0xf0f3
#define ICON_COFFEE                      0xf0f4
#define ICON_FOOD                        0xf0f5
#define ICON_DOC_TEXT                    0xf0f6
#define ICON_BUILDING                    0xf0f7
#define ICON_HOSPITAL                    0xf0f8
#define ICON_AMBULANCE                   0xf0f9
#define ICON_MEDKIT                      0xf0fa
#define ICON_FIGHTER_JET                 0xf0fb
#define ICON_BEER                        0xf0fc
#define ICON_H_SIGH                      0xf0fd
#define ICON_PLUS_SQUARED                0xf0fe
#define ICON_ANGLE_DOUBLE_LEFT           0xf100
#define ICON_ANGLE_DOUBLE_RIGHT          0xf101
#define ICON_ANGLE_DOUBLE_UP             0xf102
#define ICON_ANGLE_DOUBLE_DOWN           0xf103
#define ICON_ANGLE_LEFT                  0xf104
#define ICON_ANGLE_RIGHT                 0xf105
#define ICON_ANGLE_UP                    0xf106
#define ICON_ANGLE_DOWN                  0xf107
#define ICON_DESKTOP                     0xf108
#define ICON_LAPTOP                      0xf109
#define ICON_TABLET                      0xf10a
#define ICON_MOBILE                      0xf10b
#define ICON_CIRCLE_EMPTY                0xf10c
#define ICON_QUOTE_LEFT                  0xf10d
#define ICON_QUOTE_RIGHT                 0xf10e
#define ICON_SPINNER                     0xf110
#define ICON_CIRCLE                      0xf111
#define ICON_REPLY                       0xf112
#define ICON_GITHUB                      0xf113
#define ICON_FOLDER_EMPTY                0xf114
#define ICON_FOLDER_OPEN_EMPTY           0xf115
#define ICON_SMILE                       0xf118
#define ICON_FROWN                       0xf119
#define ICON_MEH                         0xf11a
#define ICON_GAMEPAD                     0xf11b
#define ICON_KEYBOARD                    0xf11c
#define ICON_FLAG_EMPTY                  0xf11d
#define ICON_FLAG_CHECKERED              0xf11e
#define ICON_TERMINAL                    0xf120
#define ICON_CODE                        0xf121
#define ICON_REPLY_ALL                   0xf122
#define ICON_STAR_HALF_ALT               0xf123
#define ICON_DIRECTION                   0xf124
#define ICON_CROP                        0xf125
#define ICON_FORK                        0xf126
#define ICON_UNLINK                      0xf127
#define ICON_HELP                        0xf128
#define ICON_INFO                        0xf129
#define ICON_ATTENTION_ALT               0xf12a
#define ICON_SUPERSCRIPT                 0xf12b
#define ICON_SUBSCRIPT                   0xf12c
#define ICON_ERASER                      0xf12d
#define ICON_PUZZLE                      0xf12e
#define ICON_MIC                         0xf130
#define ICON_MUTE                        0xf131
#define ICON_SHIELD                      0xf132
#define ICON_CALENDAR_EMPTY              0xf133
#define ICON_EXTINGUISHER                0xf134
#define ICON_ROCKET                      0xf135
#define ICON_MAXCDN                      0xf136
#define ICON_ANGLE_CIRCLED_LEFT          0xf137
#define ICON_ANGLE_CIRCLED_RIGHT         0xf138
#define ICON_ANGLE_CIRCLED_UP            0xf139
#define ICON_ANGLE_CIRCLED_DOWN          0xf13a
#define ICON_HTML5                       0xf13b
#define ICON_CSS3                        0xf13c
#define ICON_ANCHOR                      0xf13d
#define ICON_LOCK_OPEN_ALT               0xf13e
#define ICON_BULLSEYE                    0xf140
#define ICON_ELLIPSIS                    0xf141
#define ICON_ELLIPSIS_VERT               0xf142
#define ICON_RSS_SQUARED                 0xf143
#define ICON_PLAY_CIRCLED                0xf144
#define ICON_TICKET                      0xf145
#define ICON_MINUS_SQUARED               0xf146
#define ICON_MINUS_SQUARED_ALT           0xf147
#define ICON_LEVEL_UP                    0xf148
#define ICON_LEVEL_DOWN                  0xf149
#define ICON_OK_SQUARED                  0xf14a
#define ICON_PENCIL_SQUARED              0xf14b
#define ICON_LINK_EXT_ALT                0xf14c
#define ICON_EXPORT_ALT                  0xf14d
#define ICON_COMPASS                     0xf14e
#define ICON_EXPAND                      0xf150
#define ICON_COLLAPSE                    0xf151
#define ICON_EXPAND_RIGHT                0xf152
#define ICON_EURO                        0xf153
#define ICON_POUND                       0xf154
#define ICON_DOLLAR                      0xf155
#define ICON_RUPEE                       0xf156
#define ICON_YEN                         0xf157
#define ICON_ROUBLE                      0xf158
#define ICON_WON                         0xf159
#define ICON_BITCOIN                     0xf15a
#define ICON_DOC_INV                     0xf15b
#define ICON_DOC_TEXT_INV                0xf15c
#define ICON_SORT_NAME_UP                0xf15d
#define ICON_SORT_NAME_DOWN              0xf15e
#define ICON_SORT_ALT_UP                 0xf160
#define ICON_SORT_ALT_DOWN               0xf161
#define ICON_SORT_NUMBER_UP              0xf162
#define ICON_SORT_NUMBER_DOWN            0xf163
#define ICON_THUMBS_UP_ALT               0xf164
#define ICON_THUMBS_DOWN_ALT             0xf165
#define ICON_YOUTUBE_SQUARED             0xf166
#define ICON_YOUTUBE                     0xf167
#define ICON_XING                        0xf168
#define ICON_XING_SQUARED                0xf169
#define ICON_YOUTUBE_PLAY                0xf16a
#define ICON_DROPBOX                     0xf16b
#define ICON_STACKOVERFLOW               0xf16c
#define ICON_INSTAGRAM                   0xf16d
#define ICON_FLICKR                      0xf16e
#define ICON_ADN                         0xf170
#define ICON_BITBUCKET                   0xf171
#define ICON_BITBUCKET_SQUARED           0xf172
#define ICON_TUMBLR                      0xf173
#define ICON_TUMBLR_SQUARED              0xf174
#define ICON_DOWN                        0xf175
#define ICON_UP                          0xf176
#define ICON_LEFT                        0xf177
#define ICON_RIGHT                       0xf178
#define ICON_APPLE                       0xf179
#define ICON_WINDOWS                     0xf17a
#define ICON_ANDROID                     0xf17b
#define ICON_LINUX                       0xf17c
#define ICON_DRIBBBLE                    0xf17d
#define ICON_SKYPE                       0xf17e
#define ICON_FOURSQUARE                  0xf180
#define ICON_TRELLO                      0xf181
#define ICON_FEMALE                      0xf182
#define ICON_MALE                        0xf183
#define ICON_GITTIP                      0xf184
#define ICON_SUN                         0xf185
#define ICON_MOON                        0xf186
#define ICON_BOX                         0xf187
#define ICON_BUG                         0xf188
#define ICON_VKONTAKTE                   0xf189
#define ICON_WEIBO                       0xf18a
#define ICON_RENREN                      0xf18b
#define ICON_PAGELINES                   0xf18c
#define ICON_STACKEXCHANGE               0xf18d
#define ICON_RIGHT_CIRCLED2              0xf18e
#define ICON_LEFT_CIRCLED2               0xf190
#define ICON_COLLAPSE_LEFT               0xf191
#define ICON_DOT_CIRCLED                 0xf192
#define ICON_WHEELCHAIR                  0xf193
#define ICON_VIMEO_SQUARED               0xf194
#define ICON_TRY                         0xf195
#define ICON_PLUS_SQUARED_ALT            0xf196
#define ICON_SPACE_SHUTTLE               0xf197
#define ICON_SLACK                       0xf198
#define ICON_MAIL_SQUARED                0xf199
#define ICON_WORDPRESS                   0xf19a
#define ICON_OPENID                      0xf19b
#define ICON_BANK                        0xf19c
#define ICON_GRADUATION_CAP              0xf19d
#define ICON_YAHOO                       0xf19e
#define ICON_GOOGLE                      0xf1a0
#define ICON_REDDIT                      0xf1a1
#define ICON_REDDIT_SQUARED              0xf1a2
#define ICON_STUMBLEUPON_CIRCLED         0xf1a3
#define ICON_STUMBLEUPON                 0xf1a4
#define ICON_DELICIOUS                   0xf1a5
#define ICON_DIGG                        0xf1a6
#define ICON_PIED_PIPER_SQUARED          0xf1a7
#define ICON_PIED_PIPER_ALT              0xf1a8
#define ICON_DRUPAL                      0xf1a9
#define ICON_JOOMLA                      0xf1aa
#define ICON_LANGUAGE                    0xf1ab
#define ICON_FAX                         0xf1ac
#define ICON_BUILDING_FILLED             0xf1ad
#define ICON_CHILD                       0xf1ae
#define ICON_PAW                         0xf1b0
#define ICON_SPOON                       0xf1b1
#define ICON_CUBE                        0xf1b2
#define ICON_CUBES                       0xf1b3
#define ICON_BEHANCE                     0xf1b4
#define ICON_BEHANCE_SQUARED             0xf1b5
#define ICON_STEAM                       0xf1b6
#define ICON_STEAM_SQUARED               0xf1b7
#define ICON_RECYCLE                     0xf1b8
#define ICON_CAB                         0xf1b9
#define ICON_TAXI                        0xf1ba
#define ICON_TREE                        0xf1bb
#define ICON_SPOTIFY                     0xf1bc
#define ICON_DEVIANTART                  0xf1bd
#define ICON_SOUNDCLOUD                  0xf1be
#define ICON_DATABASE                    0xf1c0
#define ICON_FILE_PDF                    0xf1c1
#define ICON_FILE_WORD                   0xf1c2
#define ICON_FILE_EXCEL                  0xf1c3
#define ICON_FILE_POWERPOINT             0xf1c4
#define ICON_FILE_IMAGE                  0xf1c5
#define ICON_FILE_ARCHIVE                0xf1c6
#define ICON_FILE_AUDIO                  0xf1c7
#define ICON_FILE_VIDEO                  0xf1c8
#define ICON_FILE_CODE                   0xf1c9
#define ICON_VINE                        0xf1ca
#define ICON_CODEOPEN                    0xf1cb
#define ICON_JSFIDDLE                    0xf1cc
#define ICON_LIFEBUOY                    0xf1cd
#define ICON_CIRCLE_NOTCH                0xf1ce
#define ICON_REBEL                       0xf1d0
#define ICON_EMPIRE                      0xf1d1
#define ICON_GIT_SQUARED                 0xf1d2
#define ICON_GIT                         0xf1d3
#define ICON_HACKER_NEWS                 0xf1d4
#define ICON_TENCENT_WEIBO               0xf1d5
#define ICON_QQ                          0xf1d6
#define ICON_WECHAT                      0xf1d7
#define ICON_PAPER_PLANE                 0xf1d8
#define ICON_PAPER_PLANE_EMPTY           0xf1d9
#define ICON_HISTORY                     0xf1da
#define ICON_CIRCLE_THIN                 0xf1db
#define ICON_HEADER                      0xf1dc
#define ICON_PARAGRAPH                   0xf1dd
#define ICON_SLIDERS                     0xf1de
#define ICON_SHARE                       0xf1e0
#define ICON_SHARE_SQUARED               0xf1e1
#define ICON_BOMB                        0xf1e2
#define ICON_SOCCER_BALL                 0xf1e3
#define ICON_TTY                         0xf1e4
#define ICON_BINOCULARS                  0xf1e5
#define ICON_PLUG                        0xf1e6
#define ICON_SLIDESHARE                  0xf1e7
#define ICON_TWITCH                      0xf1e8
#define ICON_YELP                        0xf1e9
#define ICON_NEWSPAPER                   0xf1ea
#define ICON_WIFI                        0xf1eb
#define ICON_CALC                        0xf1ec
#define ICON_PAYPAL                      0xf1ed
#define ICON_GWALLET                     0xf1ee
#define ICON_CC_VISA                     0xf1f0
#define ICON_CC_MASTERCARD               0xf1f1
#define ICON_CC_DISCOVER                 0xf1f2
#define ICON_CC_AMEX                     0xf1f3
#define ICON_CC_PAYPAL                   0xf1f4
#define ICON_CC_STRIPE                   0xf1f5
#define ICON_BELL_OFF                    0xf1f6
#define ICON_BELL_OFF_EMPTY              0xf1f7
#define ICON_TRASH                       0xf1f8
#define ICON_COPYRIGHT                   0xf1f9
#define ICON_AT                          0xf1fa
#define ICON_EYEDROPPER                  0xf1fb
#define ICON_BRUSH                       0xf1fc
#define ICON_BIRTHDAY                    0xf1fd
#define ICON_CHART_AREA                  0xf1fe
#define ICON_CHART_PIE                   0xf200
#define ICON_CHART_LINE                  0xf201
#define ICON_LASTFM                      0xf202
#define ICON_LASTFM_SQUARED              0xf203
#define ICON_TOGGLE_OFF                  0xf204
#define ICON_TOGGLE_ON                   0xf205
#define ICON_BICYCLE                     0xf206
#define ICON_BUS                         0xf207
#define ICON_IOXHOST                     0xf208
#define ICON_ANGELLIST                   0xf209
#define ICON_CC                          0xf20a
#define ICON_SHEKEL                      0xf20b
#define ICON_MEANPATH                    0xf20c
#define ICON_BUYSELLADS                  0xf20d
#define ICON_CONNECTDEVELOP              0xf20e
#define ICON_DASHCUBE                    0xf210
#define ICON_FORUMBEE                    0xf211
#define ICON_LEANPUB                     0xf212
#define ICON_SELLSY                      0xf213
#define ICON_SHIRTSINBULK                0xf214
#define ICON_SIMPLYBUILT                 0xf215
#define ICON_SKYATLAS                    0xf216
#define ICON_CART_PLUS                   0xf217
#define ICON_CART_ARROW_DOWN             0xf218
#define ICON_DIAMOND                     0xf219
#define ICON_SHIP                        0xf21a
#define ICON_USER_SECRET                 0xf21b
#define ICON_MOTORCYCLE                  0xf21c
#define ICON_STREET_VIEW                 0xf21d
#define ICON_HEARTBEAT                   0xf21e
#define ICON_VENUS                       0xf221
#define ICON_MARS                        0xf222
#define ICON_MERCURY                     0xf223
#define ICON_TRANSGENDER                 0xf224
#define ICON_TRANSGENDER_ALT             0xf225
#define ICON_VENUS_DOUBLE                0xf226
#define ICON_MARS_DOUBLE                 0xf227
#define ICON_VENUS_MARS                  0xf228
#define ICON_MARS_STROKE                 0xf229
#define ICON_MARS_STROKE_V               0xf22a
#define ICON_MARS_STROKE_H               0xf22b
#define ICON_NEUTER                      0xf22c
#define ICON_GENDERLESS                  0xf22d
#define ICON_FACEBOOK_OFFICIAL           0xf230
#define ICON_PINTEREST                   0xf231
#define ICON_WHATSAPP                    0xf232
#define ICON_SERVER                      0xf233
#define ICON_USER_PLUS                   0xf234
#define ICON_USER_TIMES                  0xf235
#define ICON_BED                         0xf236
#define ICON_VIACOIN                     0xf237
#define ICON_TRAIN                       0xf238
#define ICON_SUBWAY                      0xf239
#define ICON_MEDIUM                      0xf23a
#define ICON_Y_COMBINATOR                0xf23b
#define ICON_OPTIN_MONSTER               0xf23c
#define ICON_OPENCART                    0xf23d
#define ICON_EXPEDITEDSSL                0xf23e
#define ICON_BATTERY_4                   0xf240
#define ICON_BATTERY_3                   0xf241
#define ICON_BATTERY_2                   0xf242
#define ICON_BATTERY_1                   0xf243
#define ICON_BATTERY_0                   0xf244
#define ICON_MOUSE_POINTER               0xf245
#define ICON_I_CURSOR                    0xf246
#define ICON_OBJECT_GROUP                0xf247
#define ICON_OBJECT_UNGROUP              0xf248
#define ICON_STICKY_NOTE                 0xf249
#define ICON_STICKY_NOTE_O               0xf24a
#define ICON_CC_JCB                      0xf24b
#define ICON_CC_DINERS_CLUB              0xf24c
#define ICON_CLONE                       0xf24d
#define ICON_BALANCE_SCALE               0xf24e
#define ICON_HOURGLASS_O                 0xf250
#define ICON_HOURGLASS_1                 0xf251
#define ICON_HOURGLASS_2                 0xf252
#define ICON_HOURGLASS_3                 0xf253
#define ICON_HOURGLASS                   0xf254
#define ICON_HAND_GRAB_O                 0xf255
#define ICON_HAND_PAPER_O                0xf256
#define ICON_HAND_SCISSORS_O             0xf257
#define ICON_HAND_LIZARD_O               0xf258
#define ICON_HAND_SPOCK_O                0xf259
#define ICON_HAND_POINTER_O              0xf25a
#define ICON_HAND_PEACE_O                0xf25b
#define ICON_TRADEMARK                   0xf25c
#define ICON_REGISTERED                  0xf25d
#define ICON_CREATIVE_COMMONS            0xf25e
#define ICON_GG                          0xf260
#define ICON_GG_CIRCLE                   0xf261
#define ICON_TRIPADVISOR                 0xf262
#define ICON_ODNOKLASSNIKI               0xf263
#define ICON_ODNOKLASSNIKI_SQUARE        0xf264
#define ICON_GET_POCKET                  0xf265
#define ICON_WIKIPEDIA_W                 0xf266
#define ICON_SAFARI                      0xf267
#define ICON_CHROME_1                    0xf268
#define ICON_FIREFOX_1                   0xf269
#define ICON_OPERA_1                     0xf26a
#define ICON_INTERNET_EXPLORER           0xf26b
#define ICON_TELEVISION                  0xf26c
#define ICON_CONTAO                      0xf26d
#define ICON_500PX                       0xf26e
#define ICON_AMAZON                      0xf270
#define ICON_CALENDAR_PLUS_O             0xf271
#define ICON_CALENDAR_MINUS_O            0xf272
#define ICON_CALENDAR_TIMES_O            0xf273
#define ICON_CALENDAR_CHECK_O            0xf274
#define ICON_INDUSTRY                    0xf275
#define ICON_MAP_PIN                     0xf276
#define ICON_MAP_SIGNS                   0xf277
#define ICON_MAP_O                       0xf278
#define ICON_MAP                         0xf279
#define ICON_COMMENTING                  0xf27a
#define ICON_COMMENTING_O                0xf27b
#define ICON_HOUZZ                       0xf27c
#define ICON_VIMEO                       0xf27d
#define ICON_BLACK_TIE                   0xf27e
#define ICON_FONT_ICONS                  0xf280
#define ICON_REDDIT_ALIEN                0xf281
#define ICON_EDGE                        0xf282
#define ICON_CREDIT_CARD_ALT             0xf283
#define ICON_CODIEPIE                    0xf284
#define ICON_MODX                        0xf285
#define ICON_FORT_AWESOME                0xf286
#define ICON_USB                         0xf287
#define ICON_PRODUCT_HUNT                0xf288
#define ICON_MIXCLOUD                    0xf289
#define ICON_SCRIBD                      0xf28a
#define ICON_PAUSE_CIRCLE                0xf28b
#define ICON_PAUSE_CIRCLE_O              0xf28c
#define ICON_STOP_CIRCLE                 0xf28d
#define ICON_STOP_CIRCLE_O               0xf28e
#define ICON_SHOPPING_BAG                0xf290
#define ICON_SHOPPING_BASKET             0xf291
#define ICON_HASHTAG                     0xf292
#define ICON_BLUETOOTH                   0xf293
#define ICON_BLUETOOTH_B                 0xf294
#define ICON_PERCENT                     0xf295
#define ICON_GITLAB                      0xf296
#define ICON_WPBEGINNER                  0xf297
#define ICON_WPFORMS                     0xf298
#define ICON_ENVIRA                      0xf299
#define ICON_UNIVERSAL_ACCESS            0xf29a
#define ICON_WHEELCHAIR_ALT              0xf29b
#define ICON_QUESTION_CIRCLE_O           0xf29c
#define ICON_BLIND                       0xf29d
#define ICON_AUDIO_DESCRIPTION           0xf29e
#define ICON_VOLUME_CONTROL_PHONE        0xf2a0
#define ICON_BRAILLE                     0xf2a1
#define ICON_ASSISTIVE_LISTENING_SYSTEMS 0xf2a2
#define ICON_AMERICAN_SIGN_LANGUAGE_     INTERPRETING 0xf2a3
#define ICON_ASL_INTERPRETING            0xf2a4
#define ICON_GLIDE                       0xf2a5
#define ICON_GLIDE_G                     0xf2a6
#define ICON_SIGN_LANGUAGE               0xf2a7
#define ICON_LOW_VISION                  0xf2a8
#define ICON_VIADEO                      0xf2a9
#define ICON_VIADEO_SQUARE               0xf2aa
#define ICON_SNAPCHAT                    0xf2ab
#define ICON_SNAPCHAT_GHOST              0xf2ac
#define ICON_SNAPCHAT_SQUARE             0xf2ad
#define ICON_PIED_PIPER                  0xf2ae
#define ICON_FIRST_ORDER                 0xf2b0
#define ICON_YOAST                       0xf2b1
#define ICON_THEMEISLE                   0xf2b2
#define ICON_GOOGLE_PLUS_CIRCLE          0xf2b3
#define ICON_FONT_AWESOME                0xf2b4
#define ICON_HANDSHAKE_O                 0xf2b5
#define ICON_ENVELOPE_OPEN               0xf2b6
#define ICON_ENVELOPE_OPEN_O             0xf2b7
#define ICON_LINODE                      0xf2b8
#define ICON_ADDRESS_BOOK                0xf2b9
#define ICON_ADDRESS_BOOK_O              0xf2ba
#define ICON_ADDRESS_CARD                0xf2bb
#define ICON_ADDRESS_CARD_O              0xf2bc
#define ICON_USER_CIRCLE                 0xf2bd
#define ICON_USER_CIRCLE_O               0xf2be
#define ICON_USER_O                      0xf2c0
#define ICON_ID_BADGE                    0xf2c1
#define ICON_ID_CARD                     0xf2c2
#define ICON_ID_CARD_O                   0xf2c3
#define ICON_QUORA                       0xf2c4
#define ICON_FREE_CODE_CAMP              0xf2c5
#define ICON_TELEGRAM                    0xf2c6
#define ICON_THERMOMETER                 0xf2c7
#define ICON_THERMOMETER_3               0xf2c8
#define ICON_THERMOMETER_2               0xf2c9
#define ICON_THERMOMETER_QUARTER         0xf2ca
#define ICON_THERMOMETER_0               0xf2cb
#define ICON_SHOWER                      0xf2cc
#define ICON_BATH                        0xf2cd
#define ICON_PODCAST                     0xf2ce
#define ICON_WINDOW_MAXIMIZE             0xf2d0
#define ICON_WINDOW_MINIMIZE             0xf2d1
#define ICON_WINDOW_RESTORE              0xf2d2
#define ICON_WINDOW_CLOSE                0xf2d3
#define ICON_WINDOW_CLOSE_O              0xf2d4
#define ICON_BANDCAMP                    0xf2d5
#define ICON_GRAV                        0xf2d6
#define ICON_ETSY                        0xf2d7
#define ICON_IMDB                        0xf2d8
#define ICON_RAVELRY                     0xf2d9
#define ICON_EERCAST                     0xf2da
#define ICON_MICROCHIP                   0xf2db
#define ICON_SNOWFLAKE_O                 0xf2dc
#define ICON_SUPERPOWERS                 0xf2dd
#define ICON_WPEXPLORER                  0xf2de
#define ICON_MEETUP                      0xf2e0
#define ICON_GITHUB_SQUARED              0xf300
#define ICON_TWITTER_SQUARED             0xf304
#define ICON_FACEBOOK_SQUARED            0xf308
#define ICON_LINKEDIN_SQUARED            0xf30c
